/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosการเดินทาง extends javax.swing.JFrame {

    /**
     * Creates new form Laosการเดินทาง
     */
    public Laosการเดินทาง() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        รถยนต์ = new javax.swing.JLabel();
        รถแท็กซี่ = new javax.swing.JLabel();
        รถเมล์ = new javax.swing.JLabel();
        รถสามล้อเล็ก = new javax.swing.JLabel();
        รถสามล้อใหญ่ = new javax.swing.JLabel();
        รถจักรยานยนต์ = new javax.swing.JLabel();
        รถจักรยาน = new javax.swing.JLabel();
        รถทัวร์ = new javax.swing.JLabel();
        รถไฟ = new javax.swing.JLabel();
        สถานีรถไฟ = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 60, 60));

        รถยนต์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถยนต์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถยนต์MouseClicked(evt);
            }
        });
        getContentPane().add(รถยนต์, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 30, 30));

        รถแท็กซี่.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถแท็กซี่.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถแท็กซี่MouseClicked(evt);
            }
        });
        getContentPane().add(รถแท็กซี่, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 30, 30));

        รถเมล์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถเมล์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถเมล์MouseClicked(evt);
            }
        });
        getContentPane().add(รถเมล์, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 30, 30));

        รถสามล้อเล็ก.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถสามล้อเล็ก.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถสามล้อเล็กMouseClicked(evt);
            }
        });
        getContentPane().add(รถสามล้อเล็ก, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 30, 30));

        รถสามล้อใหญ่.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถสามล้อใหญ่.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถสามล้อใหญ่MouseClicked(evt);
            }
        });
        getContentPane().add(รถสามล้อใหญ่, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 30, 30));

        รถจักรยานยนต์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถจักรยานยนต์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถจักรยานยนต์MouseClicked(evt);
            }
        });
        getContentPane().add(รถจักรยานยนต์, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 30, 30));

        รถจักรยาน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถจักรยาน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถจักรยานMouseClicked(evt);
            }
        });
        getContentPane().add(รถจักรยาน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 30, 30));

        รถทัวร์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถทัวร์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถทัวร์MouseClicked(evt);
            }
        });
        getContentPane().add(รถทัวร์, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 30, 30));

        รถไฟ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รถไฟ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รถไฟMouseClicked(evt);
            }
        });
        getContentPane().add(รถไฟ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 30, 30));

        สถานีรถไฟ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สถานีรถไฟ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สถานีรถไฟMouseClicked(evt);
            }
        });
        getContentPane().add(สถานีรถไฟ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/การเดินทางไป1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laos t = new Laos();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void รถยนต์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถยนต์MouseClicked
      MusicLaos.Playรถยนต์(); // TODO add your handling code here:
    }//GEN-LAST:event_รถยนต์MouseClicked

    private void รถแท็กซี่MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถแท็กซี่MouseClicked
        MusicLaos.Playรถแท็กซี่();// TODO add your handling code here:
    }//GEN-LAST:event_รถแท็กซี่MouseClicked

    private void รถเมล์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถเมล์MouseClicked
        MusicLaos.Playรถเมล์();// TODO add your handling code here:
    }//GEN-LAST:event_รถเมล์MouseClicked

    private void รถสามล้อเล็กMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถสามล้อเล็กMouseClicked
        MusicLaos.Playรถสามล้อเล็ก();// TODO add your handling code here:
    }//GEN-LAST:event_รถสามล้อเล็กMouseClicked

    private void รถสามล้อใหญ่MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถสามล้อใหญ่MouseClicked
        MusicLaos.Playรถสามล้อใหญ่();// TODO add your handling code here:
    }//GEN-LAST:event_รถสามล้อใหญ่MouseClicked

    private void รถจักรยานยนต์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถจักรยานยนต์MouseClicked
        MusicLaos.Playรถจักรยานยนต์();// TODO add your handling code here:
    }//GEN-LAST:event_รถจักรยานยนต์MouseClicked

    private void รถจักรยานMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถจักรยานMouseClicked
        MusicLaos.Playรถจักรยาน();// TODO add your handling code here:
    }//GEN-LAST:event_รถจักรยานMouseClicked

    private void รถทัวร์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถทัวร์MouseClicked
        MusicLaos.Playรถทัวร์();// TODO add your handling code here:
    }//GEN-LAST:event_รถทัวร์MouseClicked

    private void รถไฟMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รถไฟMouseClicked
        MusicLaos.Playรถไฟ();// TODO add your handling code here:
    }//GEN-LAST:event_รถไฟMouseClicked

    private void สถานีรถไฟMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สถานีรถไฟMouseClicked
        MusicLaos.Playสถานีรถไฟ();// TODO add your handling code here:
    }//GEN-LAST:event_สถานีรถไฟMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       Laosการเดินทาง1 t = new Laosการเดินทาง1();
        t.show();
        this.hide(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosการเดินทาง().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel รถจักรยาน;
    private javax.swing.JLabel รถจักรยานยนต์;
    private javax.swing.JLabel รถทัวร์;
    private javax.swing.JLabel รถยนต์;
    private javax.swing.JLabel รถสามล้อเล็ก;
    private javax.swing.JLabel รถสามล้อใหญ่;
    private javax.swing.JLabel รถเมล์;
    private javax.swing.JLabel รถแท็กซี่;
    private javax.swing.JLabel รถไฟ;
    private javax.swing.JLabel สถานีรถไฟ;
    // End of variables declaration//GEN-END:variables
}
