/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosของใช้1 extends javax.swing.JFrame {

    /**
     * Creates new form Laosของใช้1
     */
    public Laosของใช้1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        คอมพิวเตอร์ = new javax.swing.JLabel();
        อินเตอร์เน็ต = new javax.swing.JLabel();
        หนังสือ = new javax.swing.JLabel();
        สมุด = new javax.swing.JLabel();
        ปากกา = new javax.swing.JLabel();
        ดินสอ = new javax.swing.JLabel();
        กระดาษ = new javax.swing.JLabel();
        โทรทัศน์ = new javax.swing.JLabel();
        วิทยุ = new javax.swing.JLabel();
        พัดลม = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 60, 60));

        คอมพิวเตอร์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        คอมพิวเตอร์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                คอมพิวเตอร์MouseClicked(evt);
            }
        });
        getContentPane().add(คอมพิวเตอร์, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 30, 30));

        อินเตอร์เน็ต.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        อินเตอร์เน็ต.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                อินเตอร์เน็ตMouseClicked(evt);
            }
        });
        getContentPane().add(อินเตอร์เน็ต, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, 30));

        หนังสือ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        หนังสือ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                หนังสือMouseClicked(evt);
            }
        });
        getContentPane().add(หนังสือ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        สมุด.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สมุด.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สมุดMouseClicked(evt);
            }
        });
        getContentPane().add(สมุด, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 30, 30));

        ปากกา.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ปากกา.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ปากกาMouseClicked(evt);
            }
        });
        getContentPane().add(ปากกา, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 30, 30));

        ดินสอ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ดินสอ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ดินสอMouseClicked(evt);
            }
        });
        getContentPane().add(ดินสอ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 30, 30));

        กระดาษ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        กระดาษ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                กระดาษMouseClicked(evt);
            }
        });
        getContentPane().add(กระดาษ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 30, 30));

        โทรทัศน์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        โทรทัศน์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                โทรทัศน์MouseClicked(evt);
            }
        });
        getContentPane().add(โทรทัศน์, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 30, 30));

        วิทยุ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        วิทยุ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                วิทยุMouseClicked(evt);
            }
        });
        getContentPane().add(วิทยุ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 30, 30));

        พัดลม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        พัดลม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                พัดลมMouseClicked(evt);
            }
        });
        getContentPane().add(พัดลม, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/สิ่งของ2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       Loasของใช้ t = new Loasของใช้();
        t.show();
        this.hide(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void คอมพิวเตอร์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_คอมพิวเตอร์MouseClicked
       MusicLaos.Playคอมพิวเตอร์(); // TODO add your handling code here:
    }//GEN-LAST:event_คอมพิวเตอร์MouseClicked

    private void อินเตอร์เน็ตMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_อินเตอร์เน็ตMouseClicked
       MusicLaos.Playอินเตอร์เน็ต(); // TODO add your handling code here:
    }//GEN-LAST:event_อินเตอร์เน็ตMouseClicked

    private void หนังสือMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_หนังสือMouseClicked
       MusicLaos.Playหนังสือ(); // TODO add your handling code here:
    }//GEN-LAST:event_หนังสือMouseClicked

    private void สมุดMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สมุดMouseClicked
        MusicLaos.Playสมุด();// TODO add your handling code here:
    }//GEN-LAST:event_สมุดMouseClicked

    private void ปากกาMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ปากกาMouseClicked
        MusicLaos.Playปากกา();// TODO add your handling code here:
    }//GEN-LAST:event_ปากกาMouseClicked

    private void ดินสอMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ดินสอMouseClicked
        MusicLaos.Playดินสอ();// TODO add your handling code here:
    }//GEN-LAST:event_ดินสอMouseClicked

    private void กระดาษMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_กระดาษMouseClicked
        MusicLaos.Playกระดาษ();// TODO add your handling code here:
    }//GEN-LAST:event_กระดาษMouseClicked

    private void โทรทัศน์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_โทรทัศน์MouseClicked
        MusicLaos.Playโทรทัศน์();// TODO add your handling code here:
    }//GEN-LAST:event_โทรทัศน์MouseClicked

    private void วิทยุMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_วิทยุMouseClicked
        MusicLaos.Playวิทยุ();// TODO add your handling code here:
    }//GEN-LAST:event_วิทยุMouseClicked

    private void พัดลมMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_พัดลมMouseClicked
        MusicLaos.Playพัดลม();// TODO add your handling code here:
    }//GEN-LAST:event_พัดลมMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosของใช้1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosของใช้1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosของใช้1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosของใช้1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosของใช้1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel กระดาษ;
    private javax.swing.JLabel คอมพิวเตอร์;
    private javax.swing.JLabel ดินสอ;
    private javax.swing.JLabel ปากกา;
    private javax.swing.JLabel พัดลม;
    private javax.swing.JLabel วิทยุ;
    private javax.swing.JLabel สมุด;
    private javax.swing.JLabel หนังสือ;
    private javax.swing.JLabel อินเตอร์เน็ต;
    private javax.swing.JLabel โทรทัศน์;
    // End of variables declaration//GEN-END:variables
}
