/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosช้อปปิ้ง1 extends javax.swing.JFrame {

    /**
     * Creates new form Laosช้อปปิ้ง1
     */
    public Laosช้อปปิ้ง1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ซื้อ = new javax.swing.JLabel();
        ไม่ = new javax.swing.JLabel();
        ฉัน = new javax.swing.JLabel();
        สินค้า = new javax.swing.JLabel();
        เสื้อผ้า = new javax.swing.JLabel();
        รองเท้า = new javax.swing.JLabel();
        สำอาง = new javax.swing.JLabel();
        ยา = new javax.swing.JLabel();
        กระเป๋า = new javax.swing.JLabel();
        นา = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        ซื้อ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ซื้อ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ซื้อMouseClicked(evt);
            }
        });
        getContentPane().add(ซื้อ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 30, 30));

        ไม่.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ไม่.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ไม่MouseClicked(evt);
            }
        });
        getContentPane().add(ไม่, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, 30));

        ฉัน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ฉัน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ฉันMouseClicked(evt);
            }
        });
        getContentPane().add(ฉัน, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        สินค้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สินค้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สินค้าMouseClicked(evt);
            }
        });
        getContentPane().add(สินค้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 30, 30));

        เสื้อผ้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เสื้อผ้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เสื้อผ้าMouseClicked(evt);
            }
        });
        getContentPane().add(เสื้อผ้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 30, 30));

        รองเท้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รองเท้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รองเท้าMouseClicked(evt);
            }
        });
        getContentPane().add(รองเท้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 30, 30));

        สำอาง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สำอาง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สำอางMouseClicked(evt);
            }
        });
        getContentPane().add(สำอาง, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 30, 30));

        ยา.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ยา.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ยาMouseClicked(evt);
            }
        });
        getContentPane().add(ยา, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 30, 30));

        กระเป๋า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        กระเป๋า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                กระเป๋าMouseClicked(evt);
            }
        });
        getContentPane().add(กระเป๋า, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 30, 30));

        นา.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        นา.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                นาMouseClicked(evt);
            }
        });
        getContentPane().add(นา, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/ช็อปปิ้ง2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laosช้อปปิ้ง t = new Laosช้อปปิ้ง();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ซื้อMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ซื้อMouseClicked
        MusicLaos.Playซื้อ();// TODO add your handling code here:
    }//GEN-LAST:event_ซื้อMouseClicked

    private void ไม่MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ไม่MouseClicked
        MusicLaos.Playไม่ซื้อ();// TODO add your handling code here:
    }//GEN-LAST:event_ไม่MouseClicked

    private void ฉันMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ฉันMouseClicked
        MusicLaos.Playฉันอยากซื้อ();// TODO add your handling code here:
    }//GEN-LAST:event_ฉันMouseClicked

    private void สินค้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สินค้าMouseClicked
        MusicLaos.Playสินค้า();// TODO add your handling code here:
    }//GEN-LAST:event_สินค้าMouseClicked

    private void เสื้อผ้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เสื้อผ้าMouseClicked
        MusicLaos.Playเสื้อผ้า();// TODO add your handling code here:
    }//GEN-LAST:event_เสื้อผ้าMouseClicked

    private void รองเท้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รองเท้าMouseClicked
        MusicLaos.Playรองเท้า();// TODO add your handling code here:
    }//GEN-LAST:event_รองเท้าMouseClicked

    private void สำอางMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สำอางMouseClicked
        MusicLaos.Playเครื่องสำอางค์();// TODO add your handling code here:
    }//GEN-LAST:event_สำอางMouseClicked

    private void ยาMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ยาMouseClicked
        MusicLaos.Playยา();// TODO add your handling code here:
    }//GEN-LAST:event_ยาMouseClicked

    private void กระเป๋าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_กระเป๋าMouseClicked
        MusicLaos.Playกระเป๋า();// TODO add your handling code here:
    }//GEN-LAST:event_กระเป๋าMouseClicked

    private void นาMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_นาMouseClicked
        MusicLaos.Playนาฬิกา();// TODO add your handling code here:
    }//GEN-LAST:event_นาMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosช้อปปิ้ง1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel กระเป๋า;
    private javax.swing.JLabel ฉัน;
    private javax.swing.JLabel ซื้อ;
    private javax.swing.JLabel นา;
    private javax.swing.JLabel ยา;
    private javax.swing.JLabel รองเท้า;
    private javax.swing.JLabel สำอาง;
    private javax.swing.JLabel สินค้า;
    private javax.swing.JLabel เสื้อผ้า;
    private javax.swing.JLabel ไม่;
    // End of variables declaration//GEN-END:variables
}
