/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosอาหาร1 extends javax.swing.JFrame {

    /**
     * Creates new form Laosอาหาร1
     */
    public Laosอาหาร1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        แข็ง = new javax.swing.JLabel();
        น้ำผลไม้ = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        แฟเยน = new javax.swing.JLabel();
        แฟร้อน = new javax.swing.JLabel();
        นม = new javax.swing.JLabel();
        ครีม = new javax.swing.JLabel();
        หวาน = new javax.swing.JLabel();
        ไอติม = new javax.swing.JLabel();
        ขนม = new javax.swing.JLabel();
        กาแฟ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        แข็ง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        แข็ง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                แข็งMouseClicked(evt);
            }
        });
        getContentPane().add(แข็ง, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 30, 30));

        น้ำผลไม้.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        น้ำผลไม้.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                น้ำผลไม้MouseClicked(evt);
            }
        });
        getContentPane().add(น้ำผลไม้, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        แฟเยน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        แฟเยน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                แฟเยนMouseClicked(evt);
            }
        });
        getContentPane().add(แฟเยน, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 30, 30));

        แฟร้อน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        แฟร้อน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                แฟร้อนMouseClicked(evt);
            }
        });
        getContentPane().add(แฟร้อน, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 30, 30));

        นม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        นม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                นมMouseClicked(evt);
            }
        });
        getContentPane().add(นม, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 30, 30));

        ครีม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ครีม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ครีมMouseClicked(evt);
            }
        });
        getContentPane().add(ครีม, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 30, 30));

        หวาน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        หวาน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                หวานMouseClicked(evt);
            }
        });
        getContentPane().add(หวาน, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 30, 30));

        ไอติม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ไอติม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ไอติมMouseClicked(evt);
            }
        });
        getContentPane().add(ไอติม, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 30, 30));

        ขนม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ขนม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ขนมMouseClicked(evt);
            }
        });
        getContentPane().add(ขนม, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 30, 30));

        กาแฟ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/อาหาร-2.jpg"))); // NOI18N
        getContentPane().add(กาแฟ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         Laosอาหาร t = new Laosอาหาร();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void แข็งMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_แข็งMouseClicked
         MusicLaos.Playน้ำแข็ง();// TODO add your handling code here:
    }//GEN-LAST:event_แข็งMouseClicked

    private void น้ำผลไม้MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_น้ำผลไม้MouseClicked
         MusicLaos.Playน้ำผลไม้();// TODO add your handling code here:
    }//GEN-LAST:event_น้ำผลไม้MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         MusicLaos.Playกาแฟ();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void แฟเยนMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_แฟเยนMouseClicked
         MusicLaos.Playกาแฟเย็น();// TODO add your handling code here:
    }//GEN-LAST:event_แฟเยนMouseClicked

    private void แฟร้อนMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_แฟร้อนMouseClicked
         MusicLaos.Playกาแฟร้อน();// TODO add your handling code here:
    }//GEN-LAST:event_แฟร้อนMouseClicked

    private void นมMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_นมMouseClicked
         MusicLaos.Playนม();// TODO add your handling code here:
    }//GEN-LAST:event_นมMouseClicked

    private void ครีมMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ครีมMouseClicked
         MusicLaos.Playครีม();// TODO add your handling code here:
    }//GEN-LAST:event_ครีมMouseClicked

    private void หวานMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_หวานMouseClicked
         MusicLaos.Playของหวาน();// TODO add your handling code here:
    }//GEN-LAST:event_หวานMouseClicked

    private void ไอติมMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ไอติมMouseClicked
         MusicLaos.Playไอศครีม();// TODO add your handling code here:
    }//GEN-LAST:event_ไอติมMouseClicked

    private void ขนมMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ขนมMouseClicked
         MusicLaos.Playขนม();// TODO add your handling code here:
    }//GEN-LAST:event_ขนมMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosอาหาร1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel กาแฟ;
    private javax.swing.JLabel ขนม;
    private javax.swing.JLabel ครีม;
    private javax.swing.JLabel นม;
    private javax.swing.JLabel น้ำผลไม้;
    private javax.swing.JLabel หวาน;
    private javax.swing.JLabel แข็ง;
    private javax.swing.JLabel แฟร้อน;
    private javax.swing.JLabel แฟเยน;
    private javax.swing.JLabel ไอติม;
    // End of variables declaration//GEN-END:variables
}
