/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosช้อปปิ้ง extends javax.swing.JFrame {

    /**
     * Creates new form Laosช้อปปิ้ง
     */
    public Laosช้อปปิ้ง() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ห้าง = new javax.swing.JLabel();
        ร้าน = new javax.swing.JLabel();
        เท่าไร = new javax.swing.JLabel();
        ลด = new javax.swing.JLabel();
        ทอน = new javax.swing.JLabel();
        สด = new javax.swing.JLabel();
        ดิต = new javax.swing.JLabel();
        พาส = new javax.swing.JLabel();
        แพง = new javax.swing.JLabel();
        ถูก = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 60, 60));

        ห้าง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ห้าง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ห้างMouseClicked(evt);
            }
        });
        getContentPane().add(ห้าง, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 30, 30));

        ร้าน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ร้าน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ร้านMouseClicked(evt);
            }
        });
        getContentPane().add(ร้าน, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, 30));

        เท่าไร.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เท่าไร.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เท่าไรMouseClicked(evt);
            }
        });
        getContentPane().add(เท่าไร, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        ลด.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ลด.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ลดMouseClicked(evt);
            }
        });
        getContentPane().add(ลด, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 30, 30));

        ทอน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ทอน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ทอนMouseClicked(evt);
            }
        });
        getContentPane().add(ทอน, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 30, 30));

        สด.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สด.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สดMouseClicked(evt);
            }
        });
        getContentPane().add(สด, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 30, 30));

        ดิต.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ดิต.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ดิตMouseClicked(evt);
            }
        });
        getContentPane().add(ดิต, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 30, 30));

        พาส.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        พาส.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                พาสMouseClicked(evt);
            }
        });
        getContentPane().add(พาส, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 30, 30));

        แพง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        แพง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                แพงMouseClicked(evt);
            }
        });
        getContentPane().add(แพง, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 30, 30));

        ถูก.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ถูก.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ถูกMouseClicked(evt);
            }
        });
        getContentPane().add(ถูก, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/ช็อปปิ้ง1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laos t = new Laos();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ห้างMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ห้างMouseClicked
        MusicLaos.Playห้างสรรพสินค้า();// TODO add your handling code here:
    }//GEN-LAST:event_ห้างMouseClicked

    private void ร้านMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ร้านMouseClicked
        MusicLaos.Playร้านค้า();// TODO add your handling code here:
    }//GEN-LAST:event_ร้านMouseClicked

    private void เท่าไรMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เท่าไรMouseClicked
        MusicLaos.Playราคาเท่าไหร่();// TODO add your handling code here:
    }//GEN-LAST:event_เท่าไรMouseClicked

    private void ลดMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ลดMouseClicked
        MusicLaos.Playลดราคาได้ไหม();// TODO add your handling code here:
    }//GEN-LAST:event_ลดMouseClicked

    private void ทอนMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ทอนMouseClicked
        MusicLaos.Playเงินทอน();// TODO add your handling code here:
    }//GEN-LAST:event_ทอนMouseClicked

    private void สดMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สดMouseClicked
        MusicLaos.Playเงินสด();// TODO add your handling code here:
    }//GEN-LAST:event_สดMouseClicked

    private void ดิตMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ดิตMouseClicked
        MusicLaos.Playบัตรเครดิต();// TODO add your handling code here:
    }//GEN-LAST:event_ดิตMouseClicked

    private void พาสMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_พาสMouseClicked
        MusicLaos.Playพาสปอร์ต();// TODO add your handling code here:
    }//GEN-LAST:event_พาสMouseClicked

    private void แพงMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_แพงMouseClicked
        MusicLaos.Playราคาแพง();// TODO add your handling code here:
    }//GEN-LAST:event_แพงMouseClicked

    private void ถูกMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ถูกMouseClicked
        MusicLaos.Playราคาถูก();// TODO add your handling code here:
    }//GEN-LAST:event_ถูกMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       Laosช้อปปิ้ง1 t = new Laosช้อปปิ้ง1();
        t.show();
        this.hide(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosช้อปปิ้ง.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosช้อปปิ้ง().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ดิต;
    private javax.swing.JLabel ถูก;
    private javax.swing.JLabel ทอน;
    private javax.swing.JLabel พาส;
    private javax.swing.JLabel ร้าน;
    private javax.swing.JLabel ลด;
    private javax.swing.JLabel สด;
    private javax.swing.JLabel ห้าง;
    private javax.swing.JLabel เท่าไร;
    private javax.swing.JLabel แพง;
    // End of variables declaration//GEN-END:variables
}
