/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosอาหาร extends javax.swing.JFrame {

    /**
     * Creates new form Laosอาหาร
     */
    public Laosอาหาร() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        เช้า = new javax.swing.JLabel();
        เที่ยง = new javax.swing.JLabel();
        เย็น = new javax.swing.JLabel();
        ข้าว = new javax.swing.JLabel();
        ต้ม = new javax.swing.JLabel();
        ผัด = new javax.swing.JLabel();
        ก๋วยเตี๋ยว = new javax.swing.JLabel();
        แกง = new javax.swing.JLabel();
        น้ำ = new javax.swing.JLabel();
        ชา = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        เช้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เช้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เช้าMouseClicked(evt);
            }
        });
        getContentPane().add(เช้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 30, 30));

        เที่ยง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เที่ยง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เที่ยงMouseClicked(evt);
            }
        });
        getContentPane().add(เที่ยง, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, 30));

        เย็น.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เย็น.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เย็นMouseClicked(evt);
            }
        });
        getContentPane().add(เย็น, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        ข้าว.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ข้าว.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ข้าวMouseClicked(evt);
            }
        });
        getContentPane().add(ข้าว, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 30, 30));

        ต้ม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ต้ม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ต้มMouseClicked(evt);
            }
        });
        getContentPane().add(ต้ม, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 30, 30));

        ผัด.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ผัด.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ผัดMouseClicked(evt);
            }
        });
        getContentPane().add(ผัด, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 30, 30));

        ก๋วยเตี๋ยว.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ก๋วยเตี๋ยว.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ก๋วยเตี๋ยวMouseClicked(evt);
            }
        });
        getContentPane().add(ก๋วยเตี๋ยว, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 30, 30));

        แกง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        แกง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                แกงMouseClicked(evt);
            }
        });
        getContentPane().add(แกง, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 30, 30));

        น้ำ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        น้ำ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                น้ำMouseClicked(evt);
            }
        });
        getContentPane().add(น้ำ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 30, 30));

        ชา.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ชา.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ชาMouseClicked(evt);
            }
        });
        getContentPane().add(ชา, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/อาหาร 1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laos t = new Laos();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void เช้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เช้าMouseClicked
        MusicLaos.Playอาหารเช้า();// TODO add your handling code here:
    }//GEN-LAST:event_เช้าMouseClicked

    private void เที่ยงMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เที่ยงMouseClicked
        MusicLaos.Playอาหารกลางวัน();// TODO add your handling code here:
    }//GEN-LAST:event_เที่ยงMouseClicked

    private void เย็นMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เย็นMouseClicked
       MusicLaos.Playอาหารเย็น();// TODO add your handling code here:
    }//GEN-LAST:event_เย็นMouseClicked

    private void ข้าวMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ข้าวMouseClicked
        MusicLaos.Playข้าว();// TODO add your handling code here:
    }//GEN-LAST:event_ข้าวMouseClicked

    private void ต้มMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ต้มMouseClicked
        MusicLaos.Playข้าวต้ม();// TODO add your handling code here:
    }//GEN-LAST:event_ต้มMouseClicked

    private void ผัดMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ผัดMouseClicked
        MusicLaos.Playข้าวผัด();// TODO add your handling code here:
    }//GEN-LAST:event_ผัดMouseClicked

    private void ก๋วยเตี๋ยวMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ก๋วยเตี๋ยวMouseClicked
        MusicLaos.Playก๋วยเตี๋ยว();// TODO add your handling code here:
    }//GEN-LAST:event_ก๋วยเตี๋ยวMouseClicked

    private void แกงMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_แกงMouseClicked
        MusicLaos.Playน้ำแกง();// TODO add your handling code here:
    }//GEN-LAST:event_แกงMouseClicked

    private void น้ำMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_น้ำMouseClicked
        MusicLaos.Playน้ำ();// TODO add your handling code here:
    }//GEN-LAST:event_น้ำMouseClicked

    private void ชาMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ชาMouseClicked
      MusicLaos.Playน้ำชา(); // TODO add your handling code here:
    }//GEN-LAST:event_ชาMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Laosอาหาร1 t = new Laosอาหาร1();
        t.show();
        this.hide(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosอาหาร.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosอาหาร().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ก๋วยเตี๋ยว;
    private javax.swing.JLabel ข้าว;
    private javax.swing.JLabel ชา;
    private javax.swing.JLabel ต้ม;
    private javax.swing.JLabel น้ำ;
    private javax.swing.JLabel ผัด;
    private javax.swing.JLabel เช้า;
    private javax.swing.JLabel เที่ยง;
    private javax.swing.JLabel เย็น;
    private javax.swing.JLabel แกง;
    // End of variables declaration//GEN-END:variables
}
