/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosการเดินทาง1 extends javax.swing.JFrame {

    /**
     * Creates new form Laosการเดินทาง1
     */
    public Laosการเดินทาง1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        เรือ = new javax.swing.JLabel();
        ท่าเรือ = new javax.swing.JLabel();
        เครื่องบิน = new javax.swing.JLabel();
        สายการบิน = new javax.swing.JLabel();
        ตั๋วเครื่องบิน = new javax.swing.JLabel();
        ป้ายจอดรถเมล์ = new javax.swing.JLabel();
        เลี้ยวซ้าย = new javax.swing.JLabel();
        เลี้ยวขวา = new javax.swing.JLabel();
        ตรงไป = new javax.swing.JLabel();
        ตรงกันข้าม = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        เรือ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เรือ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เรือMouseClicked(evt);
            }
        });
        getContentPane().add(เรือ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 30, 30));

        ท่าเรือ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ท่าเรือ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ท่าเรือMouseClicked(evt);
            }
        });
        getContentPane().add(ท่าเรือ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 30, 30));

        เครื่องบิน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เครื่องบิน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เครื่องบินMouseClicked(evt);
            }
        });
        getContentPane().add(เครื่องบิน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 30, 30));

        สายการบิน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สายการบิน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สายการบินMouseClicked(evt);
            }
        });
        getContentPane().add(สายการบิน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 30, 30));

        ตั๋วเครื่องบิน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ตั๋วเครื่องบิน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ตั๋วเครื่องบินMouseClicked(evt);
            }
        });
        getContentPane().add(ตั๋วเครื่องบิน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 30, 30));

        ป้ายจอดรถเมล์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ป้ายจอดรถเมล์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ป้ายจอดรถเมล์MouseClicked(evt);
            }
        });
        getContentPane().add(ป้ายจอดรถเมล์, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 30, 30));

        เลี้ยวซ้าย.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เลี้ยวซ้าย.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เลี้ยวซ้ายMouseClicked(evt);
            }
        });
        getContentPane().add(เลี้ยวซ้าย, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 30, 30));

        เลี้ยวขวา.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เลี้ยวขวา.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เลี้ยวขวาMouseClicked(evt);
            }
        });
        getContentPane().add(เลี้ยวขวา, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 30, 30));

        ตรงไป.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ตรงไป.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ตรงไปMouseClicked(evt);
            }
        });
        getContentPane().add(ตรงไป, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 30, 30));

        ตรงกันข้าม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ตรงกันข้าม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ตรงกันข้ามMouseClicked(evt);
            }
        });
        getContentPane().add(ตรงกันข้าม, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/การเดินทาง2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laosการเดินทาง t = new Laosการเดินทาง();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void เรือMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เรือMouseClicked
       MusicLaos.Playเรือ(); // TODO add your handling code here:
    }//GEN-LAST:event_เรือMouseClicked

    private void ท่าเรือMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ท่าเรือMouseClicked
        MusicLaos.Playท่าเรือ(); // TODO add your handling code here:
    }//GEN-LAST:event_ท่าเรือMouseClicked

    private void เครื่องบินMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เครื่องบินMouseClicked
        MusicLaos.Playเครื่องบิน(); // TODO add your handling code here:
    }//GEN-LAST:event_เครื่องบินMouseClicked

    private void สายการบินMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สายการบินMouseClicked
         MusicLaos.Playสายการบิน();// TODO add your handling code here:
    }//GEN-LAST:event_สายการบินMouseClicked

    private void ตั๋วเครื่องบินMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ตั๋วเครื่องบินMouseClicked
         MusicLaos.Playตั๋วเครื่องบิน();// TODO add your handling code here:
    }//GEN-LAST:event_ตั๋วเครื่องบินMouseClicked

    private void ป้ายจอดรถเมล์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ป้ายจอดรถเมล์MouseClicked
         MusicLaos.Playป้ายรถเมล์();// TODO add your handling code here:
    }//GEN-LAST:event_ป้ายจอดรถเมล์MouseClicked

    private void เลี้ยวซ้ายMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เลี้ยวซ้ายMouseClicked
         MusicLaos.Playเลี้ยวซ้าย();// TODO add your handling code here:
    }//GEN-LAST:event_เลี้ยวซ้ายMouseClicked

    private void เลี้ยวขวาMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เลี้ยวขวาMouseClicked
         MusicLaos.Playเลี้ยวขวา();// TODO add your handling code here:
    }//GEN-LAST:event_เลี้ยวขวาMouseClicked

    private void ตรงไปMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ตรงไปMouseClicked
         MusicLaos.Playตรงไป();// TODO add your handling code here:
    }//GEN-LAST:event_ตรงไปMouseClicked

    private void ตรงกันข้ามMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ตรงกันข้ามMouseClicked
         MusicLaos.Playตรงกันข้าม();// TODO add your handling code here:
    }//GEN-LAST:event_ตรงกันข้ามMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosการเดินทาง1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosการเดินทาง1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ตรงกันข้าม;
    private javax.swing.JLabel ตรงไป;
    private javax.swing.JLabel ตั๋วเครื่องบิน;
    private javax.swing.JLabel ท่าเรือ;
    private javax.swing.JLabel ป้ายจอดรถเมล์;
    private javax.swing.JLabel สายการบิน;
    private javax.swing.JLabel เครื่องบิน;
    private javax.swing.JLabel เรือ;
    private javax.swing.JLabel เลี้ยวขวา;
    private javax.swing.JLabel เลี้ยวซ้าย;
    // End of variables declaration//GEN-END:variables
}
