/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Laosตัวเลข extends javax.swing.JFrame {

    /**
     * Creates new form Laosตัวเลข
     */
    public Laosตัวเลข() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ศูนย์ = new javax.swing.JLabel();
        หนึ่ง = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        สาม = new javax.swing.JLabel();
        สี่ = new javax.swing.JLabel();
        ห้า = new javax.swing.JLabel();
        หก = new javax.swing.JLabel();
        เจ็ด = new javax.swing.JLabel();
        แปด = new javax.swing.JLabel();
        เก้า = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        สอง = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        ศูนย์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ศูนย์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ศูนย์MouseClicked(evt);
            }
        });
        getContentPane().add(ศูนย์, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 30, 30));

        หนึ่ง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        หนึ่ง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                หนึ่งMouseClicked(evt);
            }
        });
        getContentPane().add(หนึ่ง, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 30, 30));

        สาม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สาม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สามMouseClicked(evt);
            }
        });
        getContentPane().add(สาม, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 30, 30));

        สี่.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สี่.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สี่MouseClicked(evt);
            }
        });
        getContentPane().add(สี่, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 30, 30));

        ห้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ห้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ห้าMouseClicked(evt);
            }
        });
        getContentPane().add(ห้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 30, 30));

        หก.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        หก.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                หกMouseClicked(evt);
            }
        });
        getContentPane().add(หก, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 30, 30));

        เจ็ด.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เจ็ด.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เจ็ดMouseClicked(evt);
            }
        });
        getContentPane().add(เจ็ด, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 30, 30));

        แปด.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        แปด.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                แปดMouseClicked(evt);
            }
        });
        getContentPane().add(แปด, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 30, 30));

        เก้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เก้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เก้าMouseClicked(evt);
            }
        });
        getContentPane().add(เก้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 60, 60));

        สอง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/การนับเลข1.jpg"))); // NOI18N
        getContentPane().add(สอง, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laos t = new Laos();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ศูนย์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ศูนย์MouseClicked
        MusicLaos.Playศูนย์();// TODO add your handling code here:
    }//GEN-LAST:event_ศูนย์MouseClicked

    private void หนึ่งMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_หนึ่งMouseClicked
        MusicLaos.Playหนึ่ง();// TODO add your handling code here:
    }//GEN-LAST:event_หนึ่งMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        MusicLaos.Playสอง();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void สามMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สามMouseClicked
        MusicLaos.Playสาม();// TODO add your handling code here:
    }//GEN-LAST:event_สามMouseClicked

    private void สี่MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สี่MouseClicked
        MusicLaos.Playสี่();// TODO add your handling code here:
    }//GEN-LAST:event_สี่MouseClicked

    private void ห้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ห้าMouseClicked
        MusicLaos.Playห้า();// TODO add your handling code here:
    }//GEN-LAST:event_ห้าMouseClicked

    private void หกMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_หกMouseClicked
        MusicLaos.Playหก();// TODO add your handling code here:
    }//GEN-LAST:event_หกMouseClicked

    private void เจ็ดMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เจ็ดMouseClicked
       MusicLaos.Playเจ็ด(); // TODO add your handling code here:
    }//GEN-LAST:event_เจ็ดMouseClicked

    private void แปดMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_แปดMouseClicked
        MusicLaos.Playแปด();// TODO add your handling code here:
    }//GEN-LAST:event_แปดMouseClicked

    private void เก้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เก้าMouseClicked
       MusicLaos.Playเก้า(); // TODO add your handling code here:
    }//GEN-LAST:event_เก้าMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Loasตัวเลข1 t = new Loasตัวเลข1();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laosตัวเลข.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laosตัวเลข.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laosตัวเลข.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laosตัวเลข.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laosตัวเลข().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel ศูนย์;
    private javax.swing.JLabel สอง;
    private javax.swing.JLabel สาม;
    private javax.swing.JLabel สี่;
    private javax.swing.JLabel หก;
    private javax.swing.JLabel หนึ่ง;
    private javax.swing.JLabel ห้า;
    private javax.swing.JLabel เก้า;
    private javax.swing.JLabel เจ็ด;
    private javax.swing.JLabel แปด;
    // End of variables declaration//GEN-END:variables
}
