/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Loasของใช้ extends javax.swing.JFrame {

    /**
     * Creates new form Loasของใช้
     */
    public Loasของใช้() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        โทรศัพท์ = new javax.swing.JLabel();
        บัตร = new javax.swing.JLabel();
        มือถือ = new javax.swing.JLabel();
        ATM = new javax.swing.JLabel();
        กุญแจ = new javax.swing.JLabel();
        ผ้าเย็น = new javax.swing.JLabel();
        ผ้าเช็ดหน้า = new javax.swing.JLabel();
        รองเท้าแตะ = new javax.swing.JLabel();
        กล้องถ่ายรูป = new javax.swing.JLabel();
        กล้องวิดีโอ = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        โทรศัพท์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        โทรศัพท์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                โทรศัพท์MouseClicked(evt);
            }
        });
        getContentPane().add(โทรศัพท์, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 30, 30));

        บัตร.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        บัตร.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                บัตรMouseClicked(evt);
            }
        });
        getContentPane().add(บัตร, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, 30));

        มือถือ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        มือถือ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                มือถือMouseClicked(evt);
            }
        });
        getContentPane().add(มือถือ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        ATM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ATM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ATMMouseClicked(evt);
            }
        });
        getContentPane().add(ATM, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 30, 30));

        กุญแจ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        กุญแจ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                กุญแจMouseClicked(evt);
            }
        });
        getContentPane().add(กุญแจ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 30, 30));

        ผ้าเย็น.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ผ้าเย็น.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ผ้าเย็นMouseClicked(evt);
            }
        });
        getContentPane().add(ผ้าเย็น, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 30, 30));

        ผ้าเช็ดหน้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ผ้าเช็ดหน้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ผ้าเช็ดหน้าMouseClicked(evt);
            }
        });
        getContentPane().add(ผ้าเช็ดหน้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 30, 30));

        รองเท้าแตะ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        รองเท้าแตะ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                รองเท้าแตะMouseClicked(evt);
            }
        });
        getContentPane().add(รองเท้าแตะ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 30, 30));

        กล้องถ่ายรูป.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        กล้องถ่ายรูป.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                กล้องถ่ายรูปMouseClicked(evt);
            }
        });
        getContentPane().add(กล้องถ่ายรูป, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 30, 30));

        กล้องวิดีโอ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        กล้องวิดีโอ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                กล้องวิดีโอMouseClicked(evt);
            }
        });
        getContentPane().add(กล้องวิดีโอ, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/สิ่งของ1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laos t = new Laos();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void โทรศัพท์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_โทรศัพท์MouseClicked
        MusicLaos.Playโทรศัพท์();// TODO add your handling code here:
    }//GEN-LAST:event_โทรศัพท์MouseClicked

    private void บัตรMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_บัตรMouseClicked
       MusicLaos.Playบัตรเติมเงิน(); // TODO add your handling code here:
    }//GEN-LAST:event_บัตรMouseClicked

    private void มือถือMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_มือถือMouseClicked
        MusicLaos.Playโทรศัพท์มือถือ();// TODO add your handling code here:
    }//GEN-LAST:event_มือถือMouseClicked

    private void ATMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ATMMouseClicked
        MusicLaos.Playตู้ATM();// TODO add your handling code here:
    }//GEN-LAST:event_ATMMouseClicked

    private void กุญแจMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_กุญแจMouseClicked
        MusicLaos.Playกุญแจ();// TODO add your handling code here:
    }//GEN-LAST:event_กุญแจMouseClicked

    private void ผ้าเย็นMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ผ้าเย็นMouseClicked
        MusicLaos.Playผ้าเย็น();// TODO add your handling code here:
    }//GEN-LAST:event_ผ้าเย็นMouseClicked

    private void ผ้าเช็ดหน้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ผ้าเช็ดหน้าMouseClicked
        MusicLaos.Playผ้าเช็ดหน้า();// TODO add your handling code here:
    }//GEN-LAST:event_ผ้าเช็ดหน้าMouseClicked

    private void รองเท้าแตะMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_รองเท้าแตะMouseClicked
       MusicLaos.Playรองเท้าแตะ(); // TODO add your handling code here:
    }//GEN-LAST:event_รองเท้าแตะMouseClicked

    private void กล้องถ่ายรูปMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_กล้องถ่ายรูปMouseClicked
       MusicLaos.Playกล้องถ่ายรูป(); // TODO add your handling code here:
    }//GEN-LAST:event_กล้องถ่ายรูปMouseClicked

    private void กล้องวิดีโอMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_กล้องวิดีโอMouseClicked
        MusicLaos.Playกล้องวิดีโอ();// TODO add your handling code here:
    }//GEN-LAST:event_กล้องวิดีโอMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Laosของใช้1 t = new Laosของใช้1();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loasของใช้.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loasของใช้.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loasของใช้.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loasของใช้.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loasของใช้().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ATM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel กล้องถ่ายรูป;
    private javax.swing.JLabel กล้องวิดีโอ;
    private javax.swing.JLabel กุญแจ;
    private javax.swing.JLabel บัตร;
    private javax.swing.JLabel ผ้าเช็ดหน้า;
    private javax.swing.JLabel ผ้าเย็น;
    private javax.swing.JLabel มือถือ;
    private javax.swing.JLabel รองเท้าแตะ;
    private javax.swing.JLabel โทรศัพท์;
    // End of variables declaration//GEN-END:variables
}
