/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Loasทักทาย extends javax.swing.JFrame {

    /**
     * Creates new form Loasทักทาย
     */
    public Loasทักทาย() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        สวัสดี = new javax.swing.JLabel();
        ขอบคุณ = new javax.swing.JLabel();
        สบายดีไหม = new javax.swing.JLabel();
        สบายดี = new javax.swing.JLabel();
        ยินดี = new javax.swing.JLabel();
        ขอให้โชคดี = new javax.swing.JLabel();
        ลาก่อน = new javax.swing.JLabel();
        นอนหลับ = new javax.swing.JLabel();
        ขอโทษ = new javax.swing.JLabel();
        ใช่ = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 60));

        สวัสดี.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สวัสดี.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สวัสดีMouseClicked(evt);
            }
        });
        getContentPane().add(สวัสดี, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 30, 30));

        ขอบคุณ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ขอบคุณ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ขอบคุณMouseClicked(evt);
            }
        });
        getContentPane().add(ขอบคุณ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 30, 30));

        สบายดีไหม.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สบายดีไหม.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สบายดีไหมMouseClicked(evt);
            }
        });
        getContentPane().add(สบายดีไหม, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 30, 30));

        สบายดี.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สบายดี.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สบายดีMouseClicked(evt);
            }
        });
        getContentPane().add(สบายดี, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 30, 30));

        ยินดี.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ยินดี.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ยินดีMouseClicked(evt);
            }
        });
        getContentPane().add(ยินดี, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 30, 30));

        ขอให้โชคดี.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ขอให้โชคดี.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ขอให้โชคดีMouseClicked(evt);
            }
        });
        getContentPane().add(ขอให้โชคดี, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 30, 30));

        ลาก่อน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ลาก่อน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ลาก่อนMouseClicked(evt);
            }
        });
        getContentPane().add(ลาก่อน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 30, 30));

        นอนหลับ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        นอนหลับ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                นอนหลับMouseClicked(evt);
            }
        });
        getContentPane().add(นอนหลับ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 30, 30));

        ขอโทษ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ขอโทษ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ขอโทษMouseClicked(evt);
            }
        });
        getContentPane().add(ขอโทษ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 30, 30));

        ใช่.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ใช่.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ใช่MouseClicked(evt);
            }
        });
        getContentPane().add(ใช่, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/ทักทาย1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Laos t = new Laos();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void สวัสดีMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สวัสดีMouseClicked
     // TODO add your handling code here:
    }//GEN-LAST:event_สวัสดีMouseClicked

    private void ขอบคุณMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ขอบคุณMouseClicked
       MusicLaos.Playขอบใจ(); // TODO add your handling code here:
    }//GEN-LAST:event_ขอบคุณMouseClicked

    private void สบายดีไหมMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สบายดีไหมMouseClicked
        MusicLaos.Playสบายดีบ่();// TODO add your handling code here:
    }//GEN-LAST:event_สบายดีไหมMouseClicked

    private void สบายดีMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สบายดีMouseClicked
        MusicLaos.Playฉันสบายดี();// TODO add your handling code here:
    }//GEN-LAST:event_สบายดีMouseClicked

    private void ยินดีMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ยินดีMouseClicked
        MusicLaos.Playยินดีที่ได่ฮู้จัก();// TODO add your handling code here:
    }//GEN-LAST:event_ยินดีMouseClicked

    private void ขอให้โชคดีMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ขอให้โชคดีMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_ขอให้โชคดีMouseClicked

    private void ลาก่อนMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ลาก่อนMouseClicked
        MusicLaos.Playลาก่อน();// TODO add your handling code here:
    }//GEN-LAST:event_ลาก่อนMouseClicked

    private void นอนหลับMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_นอนหลับMouseClicked
        MusicLaos.Playนอนหลับฝันดี();// TODO add your handling code here:
    }//GEN-LAST:event_นอนหลับMouseClicked

    private void ขอโทษMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ขอโทษMouseClicked
        MusicLaos.Playขอโทษ();// TODO add your handling code here:
    }//GEN-LAST:event_ขอโทษMouseClicked

    private void ใช่MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ใช่MouseClicked
        MusicLaos.Playใช่แล้ว();// TODO add your handling code here:
    }//GEN-LAST:event_ใช่MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         Loasทักทาย1 t = new Loasทักทาย1();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loasทักทาย().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ขอบคุณ;
    private javax.swing.JLabel ขอโทษ;
    private javax.swing.JLabel ขอให้โชคดี;
    private javax.swing.JLabel นอนหลับ;
    private javax.swing.JLabel ยินดี;
    private javax.swing.JLabel ลาก่อน;
    private javax.swing.JLabel สบายดี;
    private javax.swing.JLabel สบายดีไหม;
    private javax.swing.JLabel สวัสดี;
    private javax.swing.JLabel ใช่;
    // End of variables declaration//GEN-END:variables
}
