/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Loasตัวเลข1 extends javax.swing.JFrame {

    /**
     * Creates new form Loasตัวเลข1
     */
    public Loasตัวเลข1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        สิบ = new javax.swing.JLabel();
        วัน = new javax.swing.JLabel();
        สัปดาห์ = new javax.swing.JLabel();
        เดือน = new javax.swing.JLabel();
        ปี = new javax.swing.JLabel();
        ตอนนี้กี่โมงแล้ว = new javax.swing.JLabel();
        ชั่วโมง = new javax.swing.JLabel();
        วันหยุด = new javax.swing.JLabel();
        ตอนเช้า = new javax.swing.JLabel();
        ตอนบ่าย = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        สิบ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สิบ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สิบMouseClicked(evt);
            }
        });
        getContentPane().add(สิบ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 30, 30));

        วัน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        วัน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                วันMouseClicked(evt);
            }
        });
        getContentPane().add(วัน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 30, 30));

        สัปดาห์.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        สัปดาห์.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                สัปดาห์MouseClicked(evt);
            }
        });
        getContentPane().add(สัปดาห์, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 30, 30));

        เดือน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เดือน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เดือนMouseClicked(evt);
            }
        });
        getContentPane().add(เดือน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 30, 30));

        ปี.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ปี.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ปีMouseClicked(evt);
            }
        });
        getContentPane().add(ปี, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 30, 30));

        ตอนนี้กี่โมงแล้ว.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ตอนนี้กี่โมงแล้ว.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ตอนนี้กี่โมงแล้วMouseClicked(evt);
            }
        });
        getContentPane().add(ตอนนี้กี่โมงแล้ว, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 30, 30));

        ชั่วโมง.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ชั่วโมง.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ชั่วโมงMouseClicked(evt);
            }
        });
        getContentPane().add(ชั่วโมง, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 30, 30));

        วันหยุด.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        วันหยุด.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                วันหยุดMouseClicked(evt);
            }
        });
        getContentPane().add(วันหยุด, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 30, 30));

        ตอนเช้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ตอนเช้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ตอนเช้าMouseClicked(evt);
            }
        });
        getContentPane().add(ตอนเช้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 30, 30));

        ตอนบ่าย.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ตอนบ่าย.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ตอนบ่ายMouseClicked(evt);
            }
        });
        getContentPane().add(ตอนบ่าย, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/การนับเลข-2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       Laosตัวเลข t = new Laosตัวเลข();
        t.show();
        this.hide(); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void สิบMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สิบMouseClicked
        MusicLaos.Playสิบ();// TODO add your handling code here:
    }//GEN-LAST:event_สิบMouseClicked

    private void วันMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_วันMouseClicked
        MusicLaos.Playวัน();// TODO add your handling code here:
    }//GEN-LAST:event_วันMouseClicked

    private void สัปดาห์MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_สัปดาห์MouseClicked
        MusicLaos.Playสัปดาห์();// TODO add your handling code here:
    }//GEN-LAST:event_สัปดาห์MouseClicked

    private void เดือนMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เดือนMouseClicked
        MusicLaos.Playเดือน();// TODO add your handling code here:
    }//GEN-LAST:event_เดือนMouseClicked

    private void ปีMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ปีMouseClicked
        MusicLaos.Playปี();// TODO add your handling code here:
    }//GEN-LAST:event_ปีMouseClicked

    private void ตอนนี้กี่โมงแล้วMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ตอนนี้กี่โมงแล้วMouseClicked
        MusicLaos.Playตอนนี้กี่โมงแล้ว();// TODO add your handling code here:
    }//GEN-LAST:event_ตอนนี้กี่โมงแล้วMouseClicked

    private void ชั่วโมงMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ชั่วโมงMouseClicked
        MusicLaos.Playชั่วโมง();// TODO add your handling code here:
    }//GEN-LAST:event_ชั่วโมงMouseClicked

    private void วันหยุดMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_วันหยุดMouseClicked
        MusicLaos.Playวันหยุด();// TODO add your handling code here:
    }//GEN-LAST:event_วันหยุดMouseClicked

    private void ตอนเช้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ตอนเช้าMouseClicked
        MusicLaos.Playตอนเช้า();// TODO add your handling code here:
    }//GEN-LAST:event_ตอนเช้าMouseClicked

    private void ตอนบ่ายMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ตอนบ่ายMouseClicked
       MusicLaos.Playตอนบ่าย(); // TODO add your handling code here:
    }//GEN-LAST:event_ตอนบ่ายMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loasตัวเลข1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loasตัวเลข1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loasตัวเลข1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loasตัวเลข1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loasตัวเลข1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ชั่วโมง;
    private javax.swing.JLabel ตอนนี้กี่โมงแล้ว;
    private javax.swing.JLabel ตอนบ่าย;
    private javax.swing.JLabel ตอนเช้า;
    private javax.swing.JLabel ปี;
    private javax.swing.JLabel วัน;
    private javax.swing.JLabel วันหยุด;
    private javax.swing.JLabel สัปดาห์;
    private javax.swing.JLabel สิบ;
    private javax.swing.JLabel เดือน;
    // End of variables declaration//GEN-END:variables
}
