/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Loasทักทาย1 extends javax.swing.JFrame {

    /**
     * Creates new form Loasทักทาย1
     */
    public Loasทักทาย1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ไม่ = new javax.swing.JLabel();
        อากาศสบาย = new javax.swing.JLabel();
        ร้อน = new javax.swing.JLabel();
        หนาว = new javax.swing.JLabel();
        เช้า = new javax.swing.JLabel();
        ค่ำ = new javax.swing.JLabel();
        ชื่อ = new javax.swing.JLabel();
        ไทย = new javax.swing.JLabel();
        อายุ = new javax.swing.JLabel();
        ช่วย = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 60));

        ไม่.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ไม่.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ไม่MouseClicked(evt);
            }
        });
        getContentPane().add(ไม่, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 30, 30));

        อากาศสบาย.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        อากาศสบาย.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                อากาศสบายMouseClicked(evt);
            }
        });
        getContentPane().add(อากาศสบาย, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 30, 30));

        ร้อน.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ร้อน.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ร้อนMouseClicked(evt);
            }
        });
        getContentPane().add(ร้อน, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 30, 30));

        หนาว.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        หนาว.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                หนาวMouseClicked(evt);
            }
        });
        getContentPane().add(หนาว, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 30, 30));

        เช้า.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        เช้า.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                เช้าMouseClicked(evt);
            }
        });
        getContentPane().add(เช้า, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 30, 30));

        ค่ำ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ค่ำ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ค่ำMouseClicked(evt);
            }
        });
        getContentPane().add(ค่ำ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 30, 30));

        ชื่อ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ชื่อ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ชื่อMouseClicked(evt);
            }
        });
        getContentPane().add(ชื่อ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 30, 30));

        ไทย.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ไทย.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ไทยMouseClicked(evt);
            }
        });
        getContentPane().add(ไทย, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 30, 30));

        อายุ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        อายุ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                อายุMouseClicked(evt);
            }
        });
        getContentPane().add(อายุ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 30, 30));

        ช่วย.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/icon/1ac.png"))); // NOI18N
        ช่วย.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ช่วยMouseClicked(evt);
            }
        });
        getContentPane().add(ช่วย, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Laos/ทักทาย2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Loasทักทาย t = new Loasทักทาย();
        t.show();
        this.hide();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ไม่MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ไม่MouseClicked
        MusicLaos.Playไม่ใช่();// TODO add your handling code here:
    }//GEN-LAST:event_ไม่MouseClicked

    private void อากาศสบายMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_อากาศสบายMouseClicked
         MusicLaos.Playอากาศสบายดีจัง();// TODO add your handling code here:
    }//GEN-LAST:event_อากาศสบายMouseClicked

    private void ร้อนMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ร้อนMouseClicked
         MusicLaos.Playอากาศร้อน();// TODO add your handling code here:
    }//GEN-LAST:event_ร้อนMouseClicked

    private void หนาวMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_หนาวMouseClicked
         MusicLaos.Playอากาศหนาว();// TODO add your handling code here:
    }//GEN-LAST:event_หนาวMouseClicked

    private void เช้าMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_เช้าMouseClicked
         MusicLaos.Playสวัสดีตอนเช้า();// TODO add your handling code here:
    }//GEN-LAST:event_เช้าMouseClicked

    private void ค่ำMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ค่ำMouseClicked
         MusicLaos.Playสวัสดีตอนค่ำ();// TODO add your handling code here:
    }//GEN-LAST:event_ค่ำMouseClicked

    private void ชื่อMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ชื่อMouseClicked
         MusicLaos.Playฉันชื่อ();// TODO add your handling code here:
    }//GEN-LAST:event_ชื่อMouseClicked

    private void ไทยMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ไทยMouseClicked
         MusicLaos.Playฉันเป็นคนไทย();// TODO add your handling code here:
    }//GEN-LAST:event_ไทยMouseClicked

    private void อายุMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_อายุMouseClicked
         MusicLaos.Playฉันอายุปี();// TODO add your handling code here:
    }//GEN-LAST:event_อายุMouseClicked

    private void ช่วยMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ช่วยMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ช่วยMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loasทักทาย1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loasทักทาย1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ค่ำ;
    private javax.swing.JLabel ชื่อ;
    private javax.swing.JLabel ช่วย;
    private javax.swing.JLabel ร้อน;
    private javax.swing.JLabel หนาว;
    private javax.swing.JLabel อากาศสบาย;
    private javax.swing.JLabel อายุ;
    private javax.swing.JLabel เช้า;
    private javax.swing.JLabel ไทย;
    private javax.swing.JLabel ไม่;
    // End of variables declaration//GEN-END:variables
}
